//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufc294WindowsForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ufc294WindowsForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap costa_chimaev_ufc294graphic1_2623243286 {
            get {
                object obj = ResourceManager.GetObject("costa_chimaev_ufc294graphic1_2623243286", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightCard {
            get {
                object obj = ResourceManager.GetObject("fightCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islam Makhachev (c)	vs. Alexander Volkanovski
        ///Paulo Costa vs. Khamzat Chimaev				
        ///Magomed Ankalaev vs. Johnny Walker				
        ///Said Nurmagomedov vs. Muin Gafurov				
        ///Tim Elliott	vs. Muhammad Mokaev				
        ///Mohammad Yahya vs. Trevor Peek				
        ///Javid Basharat vs. Victor Henry				
        ///Abu Azaitar vs. Sedriques Dumas				
        ///Mike Breeden vs. Anshul Jubli				
        ///Nathaniel Wood vs. Muhammad Naimov				
        ///Victoria Dudakova vs. Jinh Yu Frey				
        ///Sharabutdin Magomedov vs. Bruno Silva.
        /// </summary>
        internal static string fightCardTxt {
            get {
                return ResourceManager.GetString("fightCardTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event will mark the promotion&apos;s 18th visit to Abu Dhabi and first since UFC 280 in October 2022.
        ///
        ///A UFC Lightweight Championship rematch between current champion Islam Makhachev and former champion Charles Oliveira was expected to headline the event. The pair previously met at UFC 280 one year prior, where Makhachev captured the vacant title by second round submission.  Former KSW Featherweight and Lightweight Champion Mateusz Gamrot is expected to serve as backup and potential replacement for this fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream its_time_ufc {
            get {
                return ResourceManager.GetStream("its_time_ufc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap makVsOlv {
            get {
                object obj = ResourceManager.GetObject("makVsOlv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ufc_fight_theme {
            get {
                return ResourceManager.GetStream("ufc_fight_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ufcLogo {
            get {
                object obj = ResourceManager.GetObject("ufcLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ufcPoster {
            get {
                object obj = ResourceManager.GetObject("ufcPoster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
